# Generated by Django 4.1.7 on 2023-03-17 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0002_user_alter_author_username_alter_comment_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('NWS', 'Новости'), ('ART', 'Статья')], default='***', max_length=3),
        ),
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_portal.author'),
        ),
    ]
