# Generated by Django 4.1.7 on 2023-03-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0003_alter_post_post_type_alter_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_rating',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_rating',
        ),
    ]
