# Generated by Django 4.1.7 on 2023-03-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0004_remove_comment_comment_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='post_rating',
            field=models.IntegerField(default=0),
        ),
    ]
